version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongo
    environment:
      - PORT=8000
      - MONGO_URI=mongodb://mongo:27017/faq_db
      - REDIS_URL=redis://redis:6379

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"

  mongo:
    image: "mongo"
    restart: always
    ports:
      - "27017:27017"
